# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CPP_row_norms_dense <- function(x, norm_code, p_norm = 2.0) {
    .Call('wordspace_CPP_row_norms_dense', PACKAGE = 'wordspace', x, norm_code, p_norm)
}

CPP_row_norms_sparse <- function(nr, nc, p, row_of, x, norm_code, p_norm = 2.0) {
    .Call('wordspace_CPP_row_norms_sparse', PACKAGE = 'wordspace', nr, nc, p, row_of, x, norm_code, p_norm)
}

CPP_col_norms_dense <- function(x, norm_code, p_norm = 2.0) {
    .Call('wordspace_CPP_col_norms_dense', PACKAGE = 'wordspace', x, norm_code, p_norm)
}

CPP_col_norms_sparse <- function(nr, nc, p, row_of, x, norm_code, p_norm = 2.0) {
    .Call('wordspace_CPP_col_norms_sparse', PACKAGE = 'wordspace', nr, nc, p, row_of, x, norm_code, p_norm)
}

