// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// CPP_row_norms_dense
NumericVector CPP_row_norms_dense(NumericMatrix x, int norm_code, double p_norm = 2.0);
RcppExport SEXP wordspace_CPP_row_norms_dense(SEXP xSEXP, SEXP norm_codeSEXP, SEXP p_normSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type norm_code(norm_codeSEXP );
        Rcpp::traits::input_parameter< double >::type p_norm(p_normSEXP );
        NumericVector __result = CPP_row_norms_dense(x, norm_code, p_norm);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// CPP_row_norms_sparse
NumericVector CPP_row_norms_sparse(int nr, int nc, IntegerVector p, IntegerVector row_of, NumericVector x, int norm_code, double p_norm = 2.0);
RcppExport SEXP wordspace_CPP_row_norms_sparse(SEXP nrSEXP, SEXP ncSEXP, SEXP pSEXP, SEXP row_ofSEXP, SEXP xSEXP, SEXP norm_codeSEXP, SEXP p_normSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type nr(nrSEXP );
        Rcpp::traits::input_parameter< int >::type nc(ncSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type row_of(row_ofSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type norm_code(norm_codeSEXP );
        Rcpp::traits::input_parameter< double >::type p_norm(p_normSEXP );
        NumericVector __result = CPP_row_norms_sparse(nr, nc, p, row_of, x, norm_code, p_norm);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// CPP_col_norms_dense
NumericVector CPP_col_norms_dense(NumericMatrix x, int norm_code, double p_norm = 2.0);
RcppExport SEXP wordspace_CPP_col_norms_dense(SEXP xSEXP, SEXP norm_codeSEXP, SEXP p_normSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type norm_code(norm_codeSEXP );
        Rcpp::traits::input_parameter< double >::type p_norm(p_normSEXP );
        NumericVector __result = CPP_col_norms_dense(x, norm_code, p_norm);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// CPP_col_norms_sparse
NumericVector CPP_col_norms_sparse(int nr, int nc, IntegerVector p, IntegerVector row_of, NumericVector x, int norm_code, double p_norm = 2.0);
RcppExport SEXP wordspace_CPP_col_norms_sparse(SEXP nrSEXP, SEXP ncSEXP, SEXP pSEXP, SEXP row_ofSEXP, SEXP xSEXP, SEXP norm_codeSEXP, SEXP p_normSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type nr(nrSEXP );
        Rcpp::traits::input_parameter< int >::type nc(ncSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type p(pSEXP );
        Rcpp::traits::input_parameter< IntegerVector >::type row_of(row_ofSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP );
        Rcpp::traits::input_parameter< int >::type norm_code(norm_codeSEXP );
        Rcpp::traits::input_parameter< double >::type p_norm(p_normSEXP );
        NumericVector __result = CPP_col_norms_sparse(nr, nc, p, row_of, x, norm_code, p_norm);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
